export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_HELP_SUCCESS = "GET_HELP_SUCCESS";
